### PR TITLE
add final newlines to json

### PR DESCRIPTION
**Pull request by zowoq**

### CODE REVIEW

**Comment by zimbatm** [comment]
the new line endings will be added on the next automated updates

**Comment by zowoq** [comment]
Some will probably never have another update, I wanted to change them all at once for consistency.

**Comment by zowoq** [comment]
https://github.com/nix-community/nixpkgs-terraform-providers-bin/pull/24

**Comment by zimbatm** [comment]
makes sense, thanks!

**Comment by zimbatm** [comment]
I just realized it might not be obvious: what happened is that I wanted to merge this PR and that commit introduced some merge conflict. Since it's auto-generated I assume it would be fine to drop it.

**Pull request merged**
